name: build

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v7

      - name: Run Swift package tests
        run: swift test
      - name: Build example app
        run: xcodebuild -project PersonnummerExample/PersonnummerExample.xcodeproj -scheme PersonnummerExample -destination 'generic/platform=iOS Simulator' build
